### ISSUE TITLE
mportError: No module named Database.Timer

### ISSUE THREAD

**Issue by cyberjeevi** [jaleelx98/Bad-Robo#6]
@kali:~/Bad-Robo$ python badrobo.py 
Traceback (most recent call last):
  File "badrobo.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 5, in <module>
ImportError: No module named Database.Timer

**Comment by jaleelx98** [comment]
Your installation is not completed

**Comment by cyberjeevi** [comment]
Bro when i clone the same directory and run tried to run on termux. Then it works. But on Pc it doesn't work.
